### ISSUE TITLE
NAs in length_m, diameter_m, width_m, height_m, and estimated_number_of_pieces columns in wood & jam data

### ISSUE THREAD

**Issue by mackerman44** [BiomarkABS/DASH#16]
Related to Issue #15  

We need to determine the best method for dealing with NAs in the length_m, diameter_m, width_m, height_m, and estimated_number_of_pieces columns in the `otg_type =` "Wood_2.csv" and `otg_type =` "Jam_3.csv" data. These are individual LWD and jam measurements that are missed in the field (or less likely, fall outside of expected QC values and we don't know how to resolve).

Currently, within `rollup_cu_wood()` and `rollup_cu_jam`, I use the median among all other measured values within a channel unit to fill in the `NA`. However,
1. This may not be the most appropriate solution, and
2. This fails when no other pieces of wood or jams were measured within the channel unit.

For now, I'm proceeding w/ the above, temporary solution, but we should identify better and then add that to the above functions for imputing missing values during the rollup step.

**Comment by KevinSee** [comment]
I wrote a function called `impute_missing_values` to the DASH package. I copied most of it from a similar function in QRFcapacity. I called that function from within `rollup_cu_wood` and `rollup_cu_jam`, instead of Mike's solution above. There are default columns to impute in each of the rollup functions, and they are the numeric ones. But if you wanted to impute things like "wet" or "ballasted", you could. 

Not sure if this is the best solution either, but it does try to impute some kind of relationship between things like length and diameter so if one is measured the other can be predicted. Is that better than just assigning a median value? Great question, and really hard to answer.

If all of those NAs are caught in the QA process, maybe the first step would be to see if any of those missing values can be estimated from the drone imagery. 

I think the best option down the road would be to build some flags into the Survey123 app so the field crew can't move on until all those fields are filled in. But that clearly doesn't help us deal with the datasets that have already been collected.

**Comment by mackerman44** [comment]
Totally agreed on all of the above! I also need to go back and make sure that NAs in any of those imputed columns in the Wood, Jam, and Undercut (other?) data are being flagged during the QC process and written out in the QC results. Doing so should ensure (or provide the opportunity), for someone to examine the drone imagery and fill in those missing values that way...if possible. The `impute_missing_values()` will be a last option, to fix the remaining. Thanks, Kevin!

I'm going to start a new issue to make sure I flag those NAs.

**Comment by mackerman44** [comment]
Considering this resolved for now. Next step will be to address Issue #17
