### ISSUE TITLE
datetime imports

### ISSUE THREAD

**Issue by mackerman44** [BiomarkABS/DASH#24]
Currently, datetime imports occurring in `read_otg_csv()` and with column specs provided in `get_otg_col_specs()` are a little problematic. Some are being read in with an AM/PM designation and in 12-hr format whereas others are being read in as 24-hr format. I initially tried to remedy using `readr::col_datetime(format = "%m/%d/%Y %H:%M")`, but to no avail.

For the moment, I'm simply reading in date time columns (e.g., **Survey Date**, **EditDate**, **CreationDate**) as `readr::col_character()`, which is maybe okay? i.e., is it up to DASH to determine datetime specifications? Or do we need to be better about date formatting in Survey123?

**Comment by KevinSee** [comment]
What if we took the character vector for Survey Date, split it by the space between the date and the time, and just kept the date? Then we transform that into a date vector. And then if we want to, we could join that date to the Survey Time column, and turn Survey Date back into a date/time object. 

How important are the EditDate and CreationDate columns? We could do something with those similar to above, and at least pull out the dates, maybe by dropping the time part, since that's what seems to be different in different files.

**Comment by KevinSee** [comment]
The pull request referenced above seems to have addressed this well, so I'm closing this issue.
