### ISSUE TITLE
QA/QC cover metrics

### ISSUE THREAD

**Issue by KevinSee** [BiomarkABS/DASH#9]
The sum of the various cover metrics can be more than 100%. However, I would suggest changing the qc_cu function to flag the following issues related to cover (instead of the current "does it sum to 100"?):

- Are some (but not all) of the cover metrics for a particular Global ID NA? These could be made 0, before moving on.

- Are any of the cover measurements in decimals, rather than multiples of 10? If they are all less than 1, this could be fixed before moving on.

- For multiples of 10, if we add all the cover metrics **_except_** "Total No Cover", it should be less than (100 - Total No Cover). If it's not, flag it.

- Is "Total No Cover" more than 100? 

- If we add all the cover metrics **_including_** "Total No Cover", it should be at least 100. Flag any that are smaller

**Comment by mackerman44** [comment]
I'm still trying to differentiate an initial QC that identified potential issues in the data from the process where values and data are actually fixed. I agree that the qc_cu function, related to cover, should be changed from "does it sum to 100?" to something more like "is it greater than or equal to 100?" or perhaps set some max value here like 200 so that it reads "is cover greater than or equal to 100, but less than 200?".

I like and agree with all of the above ideas, but this seems more appropriate for a "secondary QC process" where data are actually being changed, similar to our `DASH::rescale_percents()` function. Instead of a `rescale_percents()`, we need e.g., a `fix_cover()` function that addresses all of the above, which within it may call or use the `rescale_percents()' function.

**Comment by mackerman44** [comment]
Okay, just writing out the logic for a e.g., `fix_fish_cover()` function here to have as a record before I build it:

1. Are some, but not all, of the cover metrics for a particular Global ID NA? These could be made 0, before moving on.

2. Rescale any records that sum to 1, instead to 100.

3. Next, are any of the remaining measurements in decimals (proportions), rather than multiples of 10? If all values are less than 1 (and perhaps sum to less than 2), convert to percents (multiply by 100), before moving on.

4. Next, rescale any that sum to 90, up to 100.

5. Re-do sums.

6. For the remaining, flag anything that sums between 0 and 90 and flag anything greater than 130.

**Comment by mackerman44** [comment]
One more step 6 or 7. Identify any remaining records that are not divisible by 10.

**Comment by mackerman44** [comment]
I believe all of the above were addressed. Closing for now.
